### ISSUE TITLE
Errors,undeclared global variable x y and z

### ISSUE THREAD

**Issue by gamecompiler** [Sokomine/random_buildings#5]
Hi,

Ive got some errors, 
id uploaded a screenshot.
Is there a client related log file in minetest ?
I would prefer to give you a complete log, not just a screenshot.

![ss](https://cloud.githubusercontent.com/assets/7261213/6214364/4014835c-b5f8-11e4-9d0b-8301e026a0dd.png)

**Comment by HybridDog** [comment]
Why the close?

**Comment by ghost** [comment]
Because its working now with the "new" minetest release.

**Comment by HybridDog** [comment]
ok.
